### ISSUE TITLE
how do I get the descriptors

### ISSUE THREAD

**Issue by othane** [djpnewton/kowhai#24] opened 2013-05-06 01:42 UTC
I am looking at the tools/test code in kowhai and I can see POPULATE_PROTOCOL_GET_TREE_LIST() which will get the tree_list. But this has only pointers to the descriptors which are useless once your on a new platform, how do you get the actual descriptor ?

**Comment by djpnewton** [comment] 2013-05-06 02:27
duplicate of #25

**Closed as completed by djpnewton** 2013-05-06 02:27 UTC
